### PR TITLE
Update some stuff

### PR DESCRIPTION
**Pull request by joto**
See individual commits.

### CODE REVIEW

**Comment by joto** [comment]
Last time I looked I was the maintainer of this software. But Mapbox has locked down the repo and I can't merge my own changes any more. Anybody at Mapbox seeing this? Please either give me some rights so that I can merge stuff or approve the PR.

**Review by springmeyer — APPROVED** [review]
Looks great to me. And I presume that the protozero headers will still continue to work with C++11 if anyone needed (as these changes are only build system + catch related)?

**Comment by springmeyer** [comment]
@flippmoke @brunoabinader - either of you add a review + able to merge this?

**Comment by kkaefer** [comment]
@joto sorry for the delay. Could you please fix the remaining build failure?

**Comment by joto** [comment]
@kkaefer The build failure was not introduced by anything I changed in the code but by me updating the Github action scripts so they run on new machines. So it is a good thing we are catching that error now while it is only showing up on Debian experimental. So this PR is only one step, at least we know better where we stand after this.

I am trying to get this to a point where I can maybe fix that build failure but the issues is with the test framework which hasn't been updated in many years which the new clang version doesn't like for some reason. But to move forward I first need the CI to work.

**Comment by kkaefer** [comment]
>The build failure was not introduced by anything I changed in the code

Maybe, but the fix looks trivial (add `-Wno-c++20-extensions`)

**Comment by joto** [comment]
Usually I don't like to disable warnings, but in this case I guess there is no way around for the moment. Until I can maybe get a newer version of the tests to run that doesn't require this any more. Done now.

**Review by kkaefer — APPROVED** [review]

**Comment by kkaefer** [comment]
Well, the original warning was
```
/__w/protozero/protozero/test/t/bool/writer_test_cases.cpp:8:1: error: passing no argument for the '...' parameter of a variadic macro is a C++20 extension [-Werror,-Wc++20-extensions]
    8 | TEMPLATE_TEST_CASE("write bool field and check with libprotobuf", "",
      | ^
```

**Pull request merged**
